"""Kinda fun

Revision ID: f2a96209defd
Revises: 
Create Date: 2021-11-06 10:28:04.990255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a96209defd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'threads', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'threads', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
